/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lockerfish.ch11;

public class App {

  private int count;

  public int calculateTotal(int value) {
    try {
      return value / count;
    } catch (ArithmeticException e) {
      // This is like saying... I don't know what to do with this exception
      // so I'm going to throw a new exception with a message that is more
      // meaningful to the user.
      // Let the caller of this method handle the exception.
      throw new ArithmeticException(
          "We found a problem with this calculation. AAAA Please make sure to use the correct values.");
    }
  }

  public static void main(String[] args) {

    App app = new App();
    try {
      int total = app.calculateTotal(10);
      System.out.println("Total: " + total);

    } catch (ArithmeticException e) {
      System.out.println(e.getMessage());

      // recover by asking the user to enter a new value
    }
  }
}
